# Generated by Django 5.2.6 on 2025-10-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='country',
            new_name='country_of_residence',
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
