# Generated by Django 4.2.7 on 2026-08-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_rename_country_student_country_of_residence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='country_of_residence',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['is_active', '-created_at'], name='scholarship_active_recent'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['is_active', 'host_country'], name='scholarship_country'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['is_active', 'degree_level'], name='scholarship_degree'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['is_active', 'deadline'], name='scholarship_deadline'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_handled', '-created_at'], name='contact_inbox'),
        ),
    ]
