# Generated by Django 5.2.16 on 2026-08-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_student_citizenship_and_education_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
